#!/bin/sh
LH=/usr/lib/libhooker.dylib
if test -f "$LH"; then
  launchctl load /Library/LaunchDaemons/lh_moe.panties.discordextrasserver.plist
else
  launchctl load /Library/LaunchDaemons/cy_moe.panties.discordextrasserver.plist
fi